import Image from "next/image";
import { useEffect, useState } from "react";

export default function Home() {
  useEffect(() => {
    async function init() {
      try {
        // let res = await fetch(process.env.NEXT_PUBLIC_IMAGE_URL);
        // res = await res.json();
        // console.log(res);
        console.log("env vars...");
        console.log(process.env.NEXT_PUBLIC_RANDOM_IMAGE_URL);
      } catch (error) {
        console.log(error);
      }
    }

    init();
  }, []);

  return (
    <div className="flex flex-col items-center gap-6 justify-center mt-8">
      <div className="bg-red-500 text-white p-4 shadow-md">hello</div>
      {/* <div>{process.env.NEXT_PUBLIC_TEST}</div> */}
      <img
        src={process.env.NEXT_PUBLIC_RANDOM_IMAGE_URL}
        // src="https://random.imagecdn.app/500/500"
        alt="random image"
        className="mb-6"
      />
    </div>
  );
}

{
  /* <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div> */
}
